name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy -- -D warnings
    # - name: Test
      # run: cargo test
