name: Deploy Wasm ChessGame on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Cargo clippy (wasm)
        run: cargo clippy --target wasm32-unknown-unknown -- -D warnings

      - name: Cargo clippy (native)
        run: cargo clippy -- -D warnings

      - name: Cargo test
        run: cargo test

      - name: Install Trunk
        run: |
          curl -sL https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar xz
          mv trunk ~/.cargo/bin/

      - name: Build
        run: trunk build --release --public-url "/${{ github.event.repository.name }}/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
