
name: CI + Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo check
        run: cargo check
      - name: Clippy
        run: cargo clippy -- -D warnings
      # - name: Test
      #   run: cargo test

  deploy:
    needs: checks   # 👉 ne déploie que si checks passe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Build
        run: trunk build --release --public-url /${{ github.event.repository.name }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
