name: Deploy Wasm ChessGame on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install cargo fmt
        run: rustup component add rustfmt

      - name: Format test
        run: cargo fmt --all -- --check

      - name: Cargo check 
        run: cargo check --target wasm32-unknown-unknown

      - name: Cargo clippy
        run: cargo clippy --target wasm32-unknown-unknown -- -D warnings

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Build
        run: trunk build --release --public-url "/${{ github.event.repository.name }}/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
